name: Test

on:
  push:
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - uses: actions/checkout@v3

      - run: go test -v ./...
